-- knowledge_engineering.knowledge_requirement_tree definition

CREATE TABLE `knowledge_requirement_tree` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `scope` varchar(32) NOT NULL COMMENT '作用域/分区键，支持多棵树',
  `node_id` varchar(128) NOT NULL COMMENT '节点唯一标识',
  `parent_id` varchar(128) DEFAULT NULL COMMENT '父节点 ID，根节点为 NULL',
  `level` int NOT NULL COMMENT '层级：1=项目，2=里程碑，3=市场需求',
  `node_type` varchar(32) NOT NULL COMMENT '节点类型：project / milestone / market_requirement',
  `project_name` varchar(256) DEFAULT NULL COMMENT '项目名称（level=1）',
  `milestone_name` varchar(256) DEFAULT NULL COMMENT '里程碑名称（level=2）',
  `rdc_id` varchar(128) DEFAULT NULL COMMENT 'RDC 标识（level=3）',
  `title` varchar(512) DEFAULT NULL COMMENT '标题名称（level=3）',
  `status` varchar(64) DEFAULT NULL COMMENT '状态（level=3）',
  `main_domain` varchar(128) DEFAULT NULL COMMENT '主领域（level=3）',
  `market_req_url` varchar(1024) DEFAULT NULL COMMENT '市场需求自身链接（level=3）',
  `instance_url` varchar(1024) DEFAULT NULL COMMENT '需求实例化链接（level=3）',
  `solution_status` varchar(32) DEFAULT NULL COMMENT '需求方案状态：01-未完成/02-已完成/03-不涉及（level=3）',
  `solution_doc_url` varchar(1024) DEFAULT NULL COMMENT '方案文档链接（level=3）',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `has_children` varchar(1) NOT NULL DEFAULT 'N' COMMENT '是否有子节点 Y/N',
  `effective_flag` varchar(10) DEFAULT 'Y' COMMENT '有效标记 Y/N（软删除）',
  `sync_batch` varchar(64) DEFAULT NULL COMMENT '同步批次号',
  `operator_person` varchar(64) DEFAULT NULL COMMENT '操作人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `node_payload` json DEFAULT NULL COMMENT '拓展信息',
  `icenter_solution_urls` json DEFAULT NULL COMMENT 'iCenter方案文档链接列表（level=3）',
  `icenter_component_designs` json DEFAULT NULL COMMENT 'iCenter组件功能设计链接（level=3），key为方案URL，value为组件功能设计URL列表',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scope_node_effective` (`scope`,`node_id`,`effective_flag`),
  KEY `idx_scope_parent` (`scope`,`parent_id`,`effective_flag`,`sort_no`),
  KEY `idx_scope_level` (`scope`,`level`,`effective_flag`,`sort_no`),
  KEY `idx_scope_update_time` (`scope`,`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=4415 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='市场需求树节点缓存表';